api/urls.py
from django.urls import include, path
from api.views.organisateur import OrganisateurViewSet
from api.views.manifestation import ManifestationAutorisationViewSet, ManifestationDeclarationViewSet
from api.views.manif import InstructionViewSet
from rest_framework import routers


app_name = 'api'
router = routers.DefaultRouter()
# router.register(r'manifestations', api_views.ManifestationAllViewSet)
router.register(r'Instruction', InstructionViewSet, basename='Instruction')
router.register(r'ManifestationAutorisation', ManifestationAutorisationViewSet, basename='ManifestationAutorisation')
router.register(r'ManifestationDeclaration', ManifestationDeclarationViewSet, basename='ManifestationDeclaration')
router.register(r'Organisateur', OrganisateurViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

configuration/urls.py
from django.conf import settings
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.http import HttpResponseBadRequest

from django.contrib import admin
from django.contrib.flatpages import views as flatpages_views
from django.contrib.sitemaps import views as sitemaps_views
from django.contrib.flatpages.sitemaps import FlatPageSitemap

from core.views.ajax import validate_form
from core.views.user import (ProfileDetailView, UserUpdateView, signupagentview, signuporganisateurview,
                             EmailConfirmedView, NomPrenomChange, PasswordExpired, PasswordChangeCustomView, RenvoiMailConfirm)
from core.views.optionuser import ParametreNotificationMessagerie
from core.views.media import media_access
from organisateurs.views import StructureUpdateView
from portail.views.index import HomePage

# Todo : à supprimer après réécriture de la documentation (renvoi de l'ancienne doc vers aide/help_page)
from aide import views

admin.autodiscover()

sitemaps = {
    'flatpages': FlatPageSitemap,
}
handler400 = 'portail.views.erreur400view'
handler403 = 'portail.views.erreur403view'
handler404 = 'portail.views.erreur404view'
handler500 = 'portail.views.erreur500view'

urlpatterns = [
    # Examples:
    # path('', 'ddcs_loire.views.home', name='home'),
    # path('blog/', include('blog.urls')),

    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('sitemap\.xml', sitemaps_views.sitemap, {'sitemaps': sitemaps}),
    path('accounts/signup/', HttpResponseBadRequest),
    path('accounts/password/change/', PasswordChangeCustomView.as_view(), name='password_change_custom'),
    path('accounts/', include('allauth.urls')),
    path('accounts/passwordexpired', PasswordExpired.as_view(), name="password_expired"),
    path('accounts/send_confirm_mail/<int:pk>/', RenvoiMailConfirm.as_view(), name="send_confirm_mail"),
    path('accounts/email_confirmed', EmailConfirmedView.as_view(), name='email_confirmed'),
    path('accounts/profile/', ProfileDetailView.as_view(), name='profile'),
    path('accounts/profile/edit', UserUpdateView.as_view(), name='profile_edit'),
    path('accounts/profile/structure/edit', StructureUpdateView.as_view(), name='structure_edit'),
    path('accounts/profilte/name', NomPrenomChange.as_view(), name="nom_prenom_change"),
    path('accounts/profile/notification/edit', ParametreNotificationMessagerie.as_view(), name='parametre_notification_messagerie'),
    path('inscription/agent', signupagentview, name='inscription_agent'),
    path('inscription/organisateur', signuporganisateurview, name='inscription_organisateur'),
    path('administration/', include('administration.urls')),
    path('agreements/', include('agreements.urls')),
    path('carto/', include('carto.urls')),
    path('sub_agreements/', include('sub_agreements.urls')),
    path('instructions/', include('instructions.urls')),
    path('authorizations/', include('authorizations.urls')),
    path('declarations/', include('declarations.urls')),
    path('evaluations/', include('evaluations.urls')),
    path('incidence/', include('evaluation_incidence.urls')),
    path('notifications/', include('notifications.urls')),
    path('nouveautes/', include('nouveautes.urls')),
    path('sports/', include('sports.urls')),
    path('administrative_division/', include('administrative_division.urls')),
    path('', include('events.urls')),
    path('', include('evenements.urls')),
    path('protected_areas/', include('protected_areas.urls')),
    re_path('validate/(?P<alias>[\w\-]+)/', validate_form, name='validate'),
    path('ajax_select/', include('ajax_select.urls')),
    path('', include('portail.urls')),
    path('', HomePage.as_view(), name='home_page'),
    path('aide/', include('aide.urls')),
    path('api/', include('api.urls')),
    path('messagerie/', include('messagerie.urls')),
    path('api-auth/', include('rest_framework.urls')),
    # Todo : à réactiver après réécriture de la documentation (renvoi de l'ancienne doc vers aide/help_page)
    # Todo : à supprimer après réécriture de la documentation (renvoi de l'ancienne doc vers aide/help_page)
    #re_path('(?P<path>.+)', views.view_help_page, name="help-page"),
    path(r'webpush/', include('webpush.urls')),
]

# ici on choisis l'url media qu'on veut utiliser en debug, les non protegés sinon les protegés
if settings.DEBUG and not settings.TESTS_IN_PROGRESS:
    import debug_toolbar
    urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += re_path(r'^media/(?P<path>.*)', media_access, name='media'),

# Les flatpages doivent être toujours après les média pour eviter une interceptions des demandes de media
urlpatterns += path('', include('django.contrib.flatpages.urls')),

evenements/urls.py
# coding: utf-8
from django.urls import path, re_path

from .views.dnm import DnmCreate, DnmDetail, DnmUpdate, DnmFilesUpdate, DnmDelete
from .views.dcnm import DcnmCreate, DcnmDetail, DcnmUpdate, DcnmFilesUpdate, DcnmDelete
from .views.dnmc import DnmcCreate, DnmcDetail, DnmcUpdate, DnmcFilesUpdate, DnmcDelete
from .views.dcnmc import DcnmcCreate, DcnmcDetail, DcnmcUpdate, DcnmcFilesUpdate, DcnmcDelete
from .views.dvtm import DvtmCreate, DvtmDetail, DvtmUpdate, DvtmFilesUpdate, DvtmDelete
from .views.avtm import AvtmCreate, AvtmDetail, AvtmUpdate, AvtmFilesUpdate, AvtmDelete
from .views.avtmcir import AvtmcirCreate, AvtmcirDetail, AvtmcirUpdate, AvtmcirFilesUpdate, AvtmcirDelete
from .views.dashboard import TableauOrganisateurBody, TableauOrganisateurListe
from .views.manif import ManifInstructeurUpdate, ManifPublicDetail, ManifCartoUpdate, ManifCreateAncien, ManifUrlGen
from .views.documentcomplementaire import (
    DocumentComplementaireRequestView,
    EnvoiDocumentComplementaire,
)
from .views.sansinstance import SansInstanceManifCreate
from .views.create import CreationEvenementView
from .views.exportation import ExportPourInstructeur, ExportPourOrganisateur, ExportPourAgentlocal, ExportPourAgent


app_name = 'evenements'
urlpatterns = [

    # Tableau de bord principal
    path('tableau-de-bord-organisateur/', TableauOrganisateurBody.as_view(), name="tableau-de-bord-organisateur"),
    path('tableau-de-bord-organisateur/liste',TableauOrganisateurListe.as_view(), name="tableau_organisateur_liste"),

    path('evenement/creation/', CreationEvenementView.as_view(), name='creation_evenement'),
    path('evenement/creationancien/', ManifCreateAncien.as_view(), name='creation_ancien'),

    # Manifestation sans type (non supporté)
    path('sansinstance/add/', SansInstanceManifCreate.as_view(), name="manif_sansinstance_add"),

    # Modifications instructeur
    re_path('evenement/(?P<pk>\d+)/instruction/', ManifInstructeurUpdate.as_view(), name="manifestation_instructeur"),
    re_path('evenement/(?P<pk>\d+)/cartoedit/', ManifCartoUpdate.as_view(), name="manif_carto"),
    re_path('evenement/(?P<manif_pk>\d+)/doc_complementaire/add/', DocumentComplementaireRequestView.as_view(), name="demander_doc_complementaire"),

    path('evenement/<int:pk>/export/instructeur/', ExportPourInstructeur.as_view(), name="export_manif_instructeur"),
    path('evenement/<int:pk>/export/organisateur/', ExportPourOrganisateur.as_view(), name="export_manif_organisateur"),
    path('evenement/<int:pk>/export/agent/', ExportPourAgent.as_view(), name="export_manif_agent"),
    path('evenement/<int:pk>/export/agentlocal/', ExportPourAgentlocal.as_view(), name="export_manif_agentlocal"),

    path('doc_complementaire/<int:pk>/repondre/', EnvoiDocumentComplementaire.as_view(), name='repondre_doc_complementaire'),
    path('doc_complementaire/new/<int:pk>', EnvoiDocumentComplementaire.as_view(), name='fournir_doc_complementaire_new'),
    re_path('evenement/(?P<pk>\d+)/', ManifPublicDetail.as_view(), name="manif_detail"),
    re_path('manifestation/(?P<pk>\d+)/', ManifUrlGen.as_view(), name="manif_url"),

    # Dnm urls
    path('Dnm/add/', DnmCreate.as_view(), name="dnm_add"),
    re_path('Dnm/(?P<pk>\d+)/edit/', DnmUpdate.as_view(), name="dnm_update"),
    re_path('Dnm/(?P<pk>\d+)/edit_files/', DnmFilesUpdate.as_view(), name="dnm_files_update"),
    re_path('Dnm/(?P<pk>\d+)/delete/', DnmDelete.as_view(), name="dnm_delete"),
    re_path('Dnm/(?P<pk>\d+)/', DnmDetail.as_view(), name="dnm_detail"),

    # Dnmc urls
    path('Dnmc/add/', DnmcCreate.as_view(), name="dnmc_add"),
    re_path('Dnmc/(?P<pk>\d+)/edit/', DnmcUpdate.as_view(), name="dnmc_update"),
    re_path('Dnmc/(?P<pk>\d+)/edit_files/', DnmcFilesUpdate.as_view(), name="dnmc_files_update"),
    re_path('Dnmc/(?P<pk>\d+)/delete/', DnmcDelete.as_view(), name="dnmc_delete"),
    re_path('Dnmc/(?P<pk>\d+)/', DnmcDetail.as_view(), name="dnmc_detail"),

    # Dcnm urls
    path('Dcnm/add/', DcnmCreate.as_view(), name="dcnm_add"),
    re_path('Dcnm/(?P<pk>\d+)/edit/', DcnmUpdate.as_view(), name="dcnm_update"),
    re_path('Dcnm/(?P<pk>\d+)/edit_files/', DcnmFilesUpdate.as_view(), name="dcnm_files_update"),
    re_path('Dcnm/(?P<pk>\d+)/delete/', DcnmDelete.as_view(), name="dcnm_delete"),
    re_path('Dcnm/(?P<pk>\d+)/', DcnmDetail.as_view(), name="dcnm_detail"),

    # Dcnmc urls
    path('Dcnmc/add/', DcnmcCreate.as_view(), name="dcnmc_add"),
    re_path('Dcnmc/(?P<pk>\d+)/edit/', DcnmcUpdate.as_view(), name="dcnmc_update"),
    re_path('Dcnmc/(?P<pk>\d+)/edit_files/', DcnmcFilesUpdate.as_view(), name="dcnmc_files_update"),
    re_path('Dcnmc/(?P<pk>\d+)/delete/', DcnmcDelete.as_view(), name="dcnmc_delete"),
    re_path('Dcnmc/(?P<pk>\d+)/', DcnmcDetail.as_view(), name="dcnmc_detail"),

    # Dvtm urls
    path('Dvtm/add/', DvtmCreate.as_view(), name="dvtm_add"),
    re_path('Dvtm/(?P<pk>\d+)/edit/', DvtmUpdate.as_view(), name="dvtm_update"),
    re_path('Dvtm/(?P<pk>\d+)/edit_files/', DvtmFilesUpdate.as_view(), name="dvtm_files_update"),
    re_path('Dvtm/(?P<pk>\d+)/delete/', DvtmDelete.as_view(), name="dvtm_delete"),
    re_path('Dvtm/(?P<pk>\d+)/', DvtmDetail.as_view(), name="dvtm_detail"),

    # Avtm urls
    path('Avtm/add/', AvtmCreate.as_view(), name="avtm_add"),
    re_path('Avtm/(?P<pk>\d+)/edit/', AvtmUpdate.as_view(), name="avtm_update"),
    re_path('Avtm/(?P<pk>\d+)/edit_files/', AvtmFilesUpdate.as_view(), name="avtm_files_update"),
    re_path('Avtm/(?P<pk>\d+)/delete/', AvtmDelete.as_view(), name="avtm_delete"),
    re_path('Avtm/(?P<pk>\d+)/', AvtmDetail.as_view(), name="avtm_detail"),

    # Avtmcir urls
    path('Avtmcir/add/', AvtmcirCreate.as_view(), name="avtmcir_add"),
    re_path('Avtmcir/(?P<pk>\d+)/edit/', AvtmcirUpdate.as_view(), name="avtmcir_update"),
    re_path('Avtmcir/(?P<pk>\d+)/edit_files/', AvtmcirFilesUpdate.as_view(), name="avtmcir_files_update"),
    re_path('Avtmcir/(?P<pk>\d+)/delete/', AvtmcirDelete.as_view(), name="avtmcir_delete"),
    re_path('Avtmcir/(?P<pk>\d+)/', AvtmcirDetail.as_view(), name="avtmcir_detail"),

]

portail/urls.py
# coding: utf-8
from django.urls import path, re_path

from .views.calendar import Calendar
from .views.index import HomePage
from .views.stat import Stat
from .views.stat_instructeur import StatInstructeur


app_name = 'portail'
urlpatterns = [

    # Accueil
    path('', HomePage.as_view(), name='home_page'),

    # Calendrier
    re_path('calendar/(?P<activite>\d+)/', Calendar.as_view(), name="filtered_calendar"),
    path('calendar/', Calendar.as_view(), name="calendar"),
    path('stat/', Stat.as_view(), name="stat"),
    path('stat_instructeur/', StatInstructeur.as_view(), name="stat_instructeur"),
]

evenements/views/avtm.py
# coding: utf-8
from .manif import ManifDetail, ManifCreate, ManifUpdate, ManifFilesUpdate, ManifDelete
from ..forms.avtm import AvtmForm, AvtmFilesForm
from ..models.vtm import Avtm


class AvtmDetail(ManifDetail):
    """ Détail de manifestation """

    # Confugration
    model = Avtm


class AvtmCreate(ManifCreate):
    """ Création de manifestation """

    # Configuration
    model = Avtm
    form_class = AvtmForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['type'] = 'avtm'
        return context


class AvtmUpdate(ManifUpdate):
    """ Modification de la manifestation """

    # Configuration
    model = Avtm
    form_class = AvtmForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['type'] = 'avtm'
        return context


class AvtmFilesUpdate(ManifFilesUpdate):
    """ Modification de la manifestation """

    # Configuration
    model = Avtm
    form_class = AvtmFilesForm


class AvtmDelete(ManifDelete):
    """ Supprimer une manifestation """

    # Configuration
    model = Avtm

evenements/views/avtmcir.py
# coding: utf-8
from django import forms

from .manif import ManifDetail, ManifCreate, ManifUpdate, ManifFilesUpdate, ManifDelete
from ..forms.avtmcir import AvtmcirForm, AvtmcirFilesForm
from ..models.vtm import Avtmcir


class AvtmcirDetail(ManifDetail):
    """ Détail de la manifestation """

    # Configiratiuon
    model = Avtmcir


class AvtmcirCreate(ManifCreate):
    """ Création de la manifestation """

    # Configuration
    model = Avtmcir
    form_class = AvtmcirForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['type'] = 'avtmcir'
        return context

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['circuit_homologue'].widget = forms.HiddenInput()
        return form


class AvtmcirUpdate(ManifUpdate):
    """ Modification de la manifestation """

    # Configuration
    model = Avtmcir
    form_class = AvtmcirForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['type'] = 'avtmcir'
        return context

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['circuit_homologue'].widget = forms.HiddenInput()
        return form


class AvtmcirFilesUpdate(ManifFilesUpdate):
    """ Modification de la manifestation """

    # Configuration
    model = Avtmcir
    form_class = AvtmcirFilesForm


class AvtmcirDelete(ManifDelete):
    """ Supprimer une manifestation """

    # Configuration
    model = Avtmcir

evenements/views/create.py
import json
from django.views.generic.edit import FormView
from django.utils.decorators import method_decorator
from django.shortcuts import redirect

from sports.models.sport import Discipline
from administrative_division.models.departement import Departement
from core.util.permissions import require_role
from ..forms.create import CreationEvenementForm
from ..models.manifestation import Manif


class CreationEvenementView(FormView):
    template_name = 'evenements/recherche_creation_formulaire.html'
    form_class = CreationEvenementForm
    success_url = '/thanks/'

    # Overrides
    @method_decorator(require_role('organisateur'))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def form_valid(self, form):
        dept = Departement.objects.get(id=int(form['departement'].data))
        self.request.session['commune'] = form['ville_depart'].data
        self.request.session['discipline'] = form['discipline'].data
        self.request.session['activite'] = form['activite'].data
        self.request.session['nb_participants'] = form['nb_participants'].data
        self.request.session['emprise'] = form['emprise'].data
        self.request.session['competition'] = form['competition'].data
        self.request.session['circuit_non_permanent'] = form['circuitnonperm'].data
        self.request.session['circuit_homologue'] = form['homologue'].data
        if form['formulaire'].data in ['Avtm', 'Avtmcir']:
            if int(form['emprise'].data) in [Manif.EMPRISE['hors'], Manif.EMPRISE['partiel']]:
                self.request.session['vtm_hors_circulation'] = True
        url = '/' + form['formulaire'].data + '/add/?dept=' + dept.name
        if dept not in Departement.objects.configured():
            url = '/sansinstance/add/?dept=' + dept.name
            return redirect(url)
        else:
            return redirect(url)

    def get_context_data(self, **kwargs):
        self.request.session['extradata'] = ''
        context = super().get_context_data(**kwargs)
        context['ancien_manifs'] = Manif.objects.filter(structure=self.request.user.organisateur.structure)
        context['vtm'] = list(Discipline.objects.motorise().values_list('id', flat=True))
        context['emprise'] = json.dumps(Manif.EMPRISE)
        return context

evenements/templates/evenements/avis_pdf.html
{% load static i18n file_tags %}


<meta http-equiv="content-type" content="text/html; charset=utf-8">
<div class="head"><img src="{% static 'portail/img/Logo_vert.png' %}"/></div>

<h1>Manifestation : {{ manif }}</h1>




<div>
    <h2>Avis</h2>
    {% for avis in liste_avis %}
        <h3>{{ avis|capfirst }}</h3>
        <ul class="list-group">
            <li class="list-group-item">Date de demande de l'avis : {{ avis.date_demande }}</li>
            {% if avis.service_concerne == 'ggd' and avis.etat == 'transmis' %}
                <li class="list-group-item">L'avis a été délégué à {{ avis.get_instance.get_departement.edsr }}</li>
            {% endif %}
            {% if avis.etat == 'formaté' %}
                <li class="list-group-item">L'avis est en cours de finalisation</li>
            {% elif avis.etat == 'rendu' %}
                <li class="list-group-item">Date de rendu de l'avis : {{ avis.date_reponse|default_if_none:"Pas encore rendu" }}</li>
            {% else %}
                <li class="list-group-item">L'avis est en cours d'examen</li>
            {% endif %}
            {% if avis.etat == 'formaté' or avis.etat == 'rendu' %}
                <li class="list-group-item">Favorable : {{ avis.favorable|yesno|title }}</li>
                <li class="list-group-item">Contenu de l'avis: {{ avis.prescriptions|linebreaks }}</li>
            {% endif %}
            {% if avis.docs.all %}
                <div class="mt-2 mb-2">Pièces jointes :</div>
                {% for doc in avis.docs.all %}
                    <li class="list-group-item"> <a href="{{ doc.fichier.url }}" target="_blank">{{ doc.fichier|basename }}</a></li>
                {% endfor %}
            {% endif %}
        </ul>
    {% endfor %}
</div>



<style>
    @page  {
        size: A4;
        margin: 1cm;
    }
    .head{
        padding: 0.3cm;
    }
    .list-group-item{
        margin: 0.4em;
    }
    .card-header{
      font-weight: bold;

    }


</style>

evenements/templates/evenements/documentcomplementaire_form.html
{% extends "base_form.html" %}

{% load crispy_forms_tags %}
{% load i18n %}
{% load static %}

{% block head_title %}
    {% if manif %}
        Demande de complément d'information pour la manifestation "{{ manif }}"
    {% else %}
        Envoi de complément d'information pour la manifestation "{{ object.manif }}"
    {% endif %}
{% endblock %}

{% block page_title %}
    {% if manif %}
        <h1>Demande de complément d'information pour la manifestation "{{ manif }}"</h1>
    {% else %}
        <h1>Envoi des documents suivants : <small>{{ object.information_requise }}</small></h1>
    {% endif %}
{% endblock %}

evenements/templates/evenements/documentcomplementaire_form_provide.html
{% load static clever_selects_extras file_tags thumbail_filter i18n %}
<h5>Liste des documents complémentaires demandés :</h5>

<form class="form-horizontal" id="form_doc_compl" action="{% url 'evenements:repondre_doc_complementaire' pk=pk %}"
      enctype="multipart/form-data" method="post">
    {{ forms.management_form }}
    {% csrf_token %}
    <ul class="list-group">
        {% for form in forms %}
            <li class="list-group-item" style="margin-bottom: 1em;">

                {% for field in form %}

                    {% if field.field.widget.input_type == textarea %}
                        Demande :
                        <blockquote>
                            {% if form.instance.document_attache %}<i class="ok "></i>
                            {% else %}<i class="action-requise "></i>{% endif %}
                            {{ field.value }}</blockquote>
                        <div style="display: none">{{ field }}</div>
                    {% elif field.field.widget.input_type == 'hidden' %}
                        {{ field }}
                    {% else %}
                        {% if form.instance.document_attache %}
                            Réponse :  <a href="{{ form.instance.document_attache.url }}">{{ form.instance.document_attache.name|basename }}</a>&nbsp;&nbsp;
                            <span data-toggle="tooltip" data-placement="auto" data-html="true" class="badge badge-info"
                                  title="<img src='{{ form.instance.document_attache|thumbnail }}'"><i class="deplier no-right-margin text-white"></i>
                            </span>
                        {% else %}
                            <div>{{ field }}</div>
                        {% endif %}
                    {% endif %}

                {% endfor %}

            </li>
        {% endfor %}
    </ul>
    {% if not done %}
        <input type="submit" class="btn btn-primary" value="Enregistrer">
    {% endif %}
</form>

<script src="{% static 'portail/js/icone.js' %}" type="text/javascript"></script>

evenements/templates/evenements/evenement_carto_form.html
{% load crispy_forms_tags %}
{% load i18n verbose_tags %}
{% load static %}


    <script src="{% static 'portail/js/main.js' %}" type="text/javascript"></script>


    <form class="form-horizontal" action="{% url 'evenements:manif_carto' pk=form.instance.id %}" method="post" enctype="multipart/form-data" id="manifestation-form">
        {% if form.target.id %}<input type="hidden" name="id" id="id_id" value="{{ form.target.id }}">{% endif %}
        {% crispy form %}
        {{ form.media }}
        <div class="form-actions">
            <input id="submit-id-save" class="btn btn-primary" type="submit" value="Enregistrer" name="save">
            {% if form.instance.id %}
                <a class="btn btn-danger" id="carto_annul" href="javascript:history.back()">Annuler</a>
            {% endif %}

        </div>
    </form>
    <script src='{% static "portail/js/file-validator.js" %}' type="text/javascript"></script>
    <script src='{% static "libs/autogrow/jquery.ns-autogrow.min.js" %}' type="text/javascript"></script>
    <script src='{% static "portail/js/jquery.liveValidation.js" %}' type="text/javascript"></script>
    <script src='{% static "evenements/js/manifestation_formulaire.js" %}' type="text/javascript"></script>
{#    <script>jQuery.fn.preventDoubleSubmission = function(){}</script>#}

evenements/templates/evenements/evenementpublic_detail.html
{% extends "base.html" %}


{% load i18n %}

{% block head_title %}{{ object|capfirst }}{% endblock %}
{% block page_title %}
    <h1>{{ object|capfirst }}</h1>
{% endblock %}

{% block content %}
    {% if request.user == object.structure.organisateur.user %}
        <div class="alert alert-warning">Cette manifestation se déroule dans un département qui n'est pas abonné à cette plateforme.<br>
            <strong>Le dossier n'a pas été transmis au service instructeur.</strong><br>
            N'hésitez pas à prendre contact avec le service d'instruction de votre département pour suivre leur consignes.
        </div>
    {% endif %}
    <div class="row">
        <div class="col-sm-6">
            <div class="card ">
                {% if not object.visible_dans_calendrier %}
                    <div class="card-body"><span class="text-danger">La manifestation a été masquée du calendrier public par l'{{ object.prive | yesno:"organisateur,instructeur" }}</span></div>
                {% endif %}
                <div class="card-body">{{ object.description|linebreaks }}</div>
                <ul class="list-group">
                    <li class="list-group-item"><strong><i class="date"></i>Début : </strong>{{ object.date_debut|date:"d F Y - H:i" }}</li>
                    <li class="list-group-item"><strong><i class="date"></i>Fin : </strong>{{ object.date_fin|date:"d F Y - H:i" }}</li>
                    <li class="list-group-item"><strong><i class="activite"></i> Sport : </strong>{{ object.activite.discipline }} - {{ object.activite }}</li>
                    <li class="list-group-item"><strong><i class="voie-publique"></i> Sur voie publique ou ouverte à la circulation publique : </strong>{{ object.activite|yesno|title }}</li>
                    <li class="list-group-item"><strong><i class="lieu"></i> Commune de départ : </strong>{{ object.ville_depart|capfirst }}</li>
                    <li class="list-group-item"><strong><i class="lieu"></i> Communes traversées : </strong>
                        {% for ville in object.get_villes_traversees %}
                            {% if forloop.last %}
                                {{ ville }}.
                            {% else %}
                                {{ ville }},
                            {% endif %}
                        {% endfor %}
                    </li>
                </ul>
            {% if object.afficher_adresse_structure %}
                <div class="card-body">
                    <strong>Informations de contact :</strong><br>
                    {% with object.structure as structure %}
                        {{ structure.name }}<br>
                        {{ structure.address }}<br>
                        <span id="ctx-help-insee-code">{{ structure.commune.code }}</span> {{ structure.commune }}<br>
                        {% if structure.website %}<strong>Site web :</strong> {{ structure.website|urlize }}<br>{% endif %}
                        <strong>Téléphone :</strong> {{ structure.phone }}<br>
                    {% endwith %}

                </div>
            {% endif %}
            </div>
        </div>
        {% comment %}
        <div class="col-sm-6">
            {% include 'events/map.html' %}
        </div>
        {% endcomment %}
    </div>
    {% if object.get_type_manif %}
        <a href="{% url 'portail:calendar' %}" class="btn btn-primary">
            <i class="date"></i> Retour au calendrier des manifestations sportives</a>
    {% else %}
        <a href="{% url 'evenements:tableau-de-bord-organisateur' %}" class="btn btn-primary">
            <i class="tableau-de-bord"></i> Retour au tableau de bord</a>
    {% endif %}
{% endblock %}